### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Alexh100** [rnwood/smtpserver#138]
Hello, 

Do you have any contact info? just want to ask you some questions, if that's possible.

Thanks

**Comment by rnwood** [comment]
Hi Alex

rob@<GitHub username>.co.uk
________________________________
From: Alexh100 ***@***.***>
Sent: Saturday, April 17, 2021 11:23:32 PM
To: rnwood/smtpserver ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rnwood/smtpserver] Hello (#138)


Hello,

Do you have any contact info? just want to ask you some questions, if that's possible.

Thanks
