### ISSUE TITLE
The same code does work on Windows but not on Linux

### ISSUE THREAD

**Issue by WaldemarCichon** [rnwood/smtpserver#147]
I developed a small SMTP-Server which is used to receive mails sent by my China-built cameras for wild watching. They sent two kinds of mails and I wrote an dotnet application which works on my windows server without any problem. 
Because I want to have the windows server as a development server reachable also from my Mac I have deployed the complete solution to a standard Ubuntu 20.x powered V-Server. 
The camera is working as expected, as when I will send the mail to the Windows server but much slower. But it states that the mail was sent without any errors.
But on the console I see only that the start and end events are fired. The Auth-Event and also the main receive-Event ist not fired. 

I can provide you access to my git or even sent mails to a server on which you can try to receive the message.

**Comment by rnwood** [comment]
Closing stale issue.
